apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: podgroups.scheduling.volcano.sh
spec:
  group: scheduling.volcano.sh
  names:
    kind: PodGroup
    listKind: PodGroupList
    plural: podgroups
    shortNames:
    - pg
    - podgroup-v1beta1
    singular: podgroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: STATUS
      type: string
    - jsonPath: .spec.minMember
      name: minMember
      type: integer
    - jsonPath: .status.running
      name: RUNNINGS
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    - jsonPath: .spec.queue
      name: QUEUE
      priority: 1
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: PodGroup is a collection of Pod; used for batch workload.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              Specification of the desired behavior of the pod group.
              More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
            properties:
              minMember:
                description: |-
                  MinMember defines the minimal number of members/tasks to run the pod group;
                  if there's not enough resources to start all tasks, the scheduler
                  will not start anyone.
                format: int32
                minimum: 0
                type: integer
              minResources:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: |-
                  MinResources defines the minimal resource of members/tasks to run the pod group;
                  if there's not enough resources to start all tasks, the scheduler
                  will not start anyone.
                type: object
              minTaskMember:
                additionalProperties:
                  format: int32
                  type: integer
                description: |-
                  MinTaskMember defines the minimal number of pods to run for each task in the pod group;
                  if there's not enough resources to start each task, the scheduler
                  will not start anyone.
                  SubGroupPolicy covers all capabilities of minTaskMember, while providing richer network topology and Gang scheduling management capabilities.
                  Recommend using SubGroupPolicy to uniformly manage Gang scheduling for each Task group.
                type: object
              networkTopology:
                description: NetworkTopology defines the NetworkTopology config, this
                  field works in conjunction with network topology feature and hyperNode
                  CRD.
                properties:
                  highestTierAllowed:
                    description: HighestTierAllowed specifies the highest tier that
                      a job allowed to cross when scheduling.
                    minimum: 0
                    type: integer
                  highestTierName:
                    description: |-
                      HighestTierName specifies the highest tier name that a job allowed to cross when scheduling.
                      HighestTierName and HighestTierAllowed cannot be set simultaneously.
                    maxLength: 253
                    type: string
                  mode:
                    default: hard
                    description: Mode specifies the mode of the network topology constrain.
                    enum:
                    - hard
                    - soft
                    type: string
                type: object
              priorityClassName:
                description: |-
                  If specified, indicates the PodGroup's priority. "system-node-critical" and
                  "system-cluster-critical" are two special keywords which indicate the
                  highest priorities with the former being the highest priority. Any other
                  name must be defined by creating a PriorityClass object with that name.
                  If not specified, the PodGroup priority will be default or zero if there is no
                  default.
                maxLength: 253
                type: string
              queue:
                default: default
                description: |-
                  Queue defines the queue to allocate resource for PodGroup; if queue does not exist,
                  the PodGroup will not be scheduled. Defaults to `default` Queue with the lowest weight.
                maxLength: 253
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                type: string
              subGroupPolicy:
                description: |-
                  Compared with minTaskMember, it offers more comprehensive topology scheduling and Gang scheduling management capabilities.
                  Concurrent use with minTaskMember is not recommended, and SubGroupPolicy is the long-term evolution direction.
                items:
                  properties:
                    labelSelector:
                      description: |-
                        LabelSelector is used to find matching pods.
                        Pods that match this label selector are counted to determine the number of pods
                        in their corresponding topology domain.
                      properties:
                        matchExpressions:
                          description: matchExpressions is a list of label selector
                            requirements. The requirements are ANDed.
                          items:
                            description: |-
                              A label selector requirement is a selector that contains values, a key, and an operator that
                              relates the key and values.
                            properties:
                              key:
                                description: key is the label key that the selector
                                  applies to.
                                type: string
                              operator:
                                description: |-
                                  operator represents a key's relationship to a set of values.
                                  Valid operators are In, NotIn, Exists and DoesNotExist.
                                type: string
                              values:
                                description: |-
                                  values is an array of string values. If the operator is In or NotIn,
                                  the values array must be non-empty. If the operator is Exists or DoesNotExist,
                                  the values array must be empty. This array is replaced during a strategic
                                  merge patch.
                                items:
                                  type: string
                                type: array
                                x-kubernetes-list-type: atomic
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                          x-kubernetes-list-type: atomic
                        matchLabels:
                          additionalProperties:
                            type: string
                          description: |-
                            matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                            map is equivalent to an element of matchExpressions, whose key field is "key", the
                            operator is "In", and the values array contains only "value". The requirements are ANDed.
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    matchLabelKeys:
                      description: |-
                        MatchLabelKeys: A label-based grouping configuration field for Pods, defining filtering rules for grouping label keys
                        Core function: Refine grouping of Pods that meet LabelSelector criteria by label attributes, with the following rules and constraints:
                        1. Scope: Only applies to Pods matching the predefined LabelSelector
                        2. Grouping rule: Specify one or more label keys; Pods containing the target label keys with exactly the same corresponding label values are grouped together
                        3. Policy constraint: Pods in the same group follow a unified NetworkTopology policy to achieve group-level network behavior governance
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: atomic
                    minSubGroups:
                      default: 0
                      description: |-
                        MinSubGroups: Minimum number of subgroups required to trigger scheduling. Scheduling is initiated only if cluster resources meet the requirements of at least this number of subgroups.
                        Subgroup-level Gang Scheduling
                      format: int32
                      minimum: 0
                      type: integer
                    name:
                      description: Name specifies the name of SubGroupPolicy
                      maxLength: 253
                      type: string
                    networkTopology:
                      description: NetworkTopology defines the NetworkTopology config,
                        this field works in conjunction with network topology feature
                        and hyperNode CRD.
                      properties:
                        highestTierAllowed:
                          description: HighestTierAllowed specifies the highest tier
                            that a job allowed to cross when scheduling.
                          minimum: 0
                          type: integer
                        highestTierName:
                          description: |-
                            HighestTierName specifies the highest tier name that a job allowed to cross when scheduling.
                            HighestTierName and HighestTierAllowed cannot be set simultaneously.
                          maxLength: 253
                          type: string
                        mode:
                          default: hard
                          description: Mode specifies the mode of the network topology
                            constrain.
                          enum:
                          - hard
                          - soft
                          type: string
                      type: object
                    subGroupSize:
                      default: 1
                      description: |-
                        SubGroupSize defines the number of pods in each sub-affinity group.
                        Only when a subGroup of pods, with a size of "subGroupSize", can satisfy the network topology constraint then will the subGroup be scheduled.
                      format: int32
                      minimum: 1
                      type: integer
                  type: object
                type: array
            type: object
          status:
            description: |-
              Status represents the current information about a pod group.
              This data may not be up to date.
            properties:
              conditions:
                description: The conditions of PodGroup.
                items:
                  description: PodGroupCondition contains details for the current
                    state of this pod group.
                  properties:
                    lastTransitionTime:
                      description: Last time the phase transitioned from another to
                        current phase.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the phase's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition.
                      type: string
                    transitionID:
                      description: The ID of condition transition.
                      type: string
                    type:
                      description: Type is the type of the condition
                      type: string
                  type: object
                type: array
              failed:
                description: The number of pods which reached phase Failed.
                format: int32
                minimum: 0
                type: integer
              phase:
                description: Current phase of PodGroup.
                enum:
                - Pending
                - Running
                - Unknown
                - Inqueue
                - Completed
                type: string
              running:
                description: The number of actively running pods.
                format: int32
                minimum: 0
                type: integer
              succeeded:
                description: The number of pods which reached phase Succeeded.
                format: int32
                minimum: 0
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
