language: go

sudo: required

env:
  - HOME=/home/travis

services:
  - docker

go:
  - "1.10"

go_import_path: github.com/kubernetes-incubator/kube-arbitrator

install:
  - go get -u github.com/golang/lint/golint

before_script:
  - export TEST_LOG_LEVEL=4

script:
  - make verify
  - make
  - make run-test
  - make e2e

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
