dist: xenial
language: go
go:
  - '1.11.x'
sudo: required
env:
  - HOME=/home/travis
services:
  - docker
go_import_path: volcano.sh/volcano
jobs:
  include:
    - stage: publish release
      before_deploy:
        - export TRAVIS_TAG=$(git describe --tags)
      script:
        - echo "publish release to github & dockerhub"
      deploy:
        - provider: script
          script: make TAG=${TRAVIS_TAG} RELEASE_VER=${TRAVIS_TAG} release
          on:
            tags: true
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: _output/release/volcano-${TRAVIS_TAG}-${OSTYPE}.tar.gz
          skip_cleanup: true
          on:
            tags: true
            branch: master
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
