language: go

sudo: required

env:
  - HOME=/home/travis

services:
  - docker

go:
  - "1.11"

go_import_path: github.com/kubernetes-sigs/kube-batch

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - export TEST_LOG_LEVEL=4

script:
  - make verify
  - make
  - make run-test
  - make e2e

