dist: xenial
language: go
go:
  - '1.11.x'
sudo: required
env:
  - HOME=/home/travis
services:
  - docker
go_import_path: volcano.sh/volcano
jobs:
  include:
    - stage: Golint & Gofmt
      before_script:
        - go get -u golang.org/x/lint/golint
      script:
        - make
        - make verify
    - stage: E2E Tests
      before_script:
        # Download kubectl
        - sudo apt-get update && sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update
        - sudo apt-get install -y kubectl
        # Download kind binary (0.2.0)
        - curl -o /usr/local/bin/kind -L https://github.com/kubernetes-sigs/kind/releases/download/0.2.0/kind-linux-amd64
        - chmod +x /usr/local/bin/kind
      script:
        - make cli
        - make docker
        - make e2e-test-kind
