apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-admission

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-admission
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-admission-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-admission
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-admission
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission
    admission: "true"
  name: {{ .Release.Name }}-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission
      admission: "true"
  template:
    metadata:
      labels:
        app: admission
        admission: "true"
    spec:
      serviceAccount: {{ .Release.Name }}-admission
      containers:
        - args:
            - --tls-cert-file=/admission.local.config/certificates/tls.crt
            - --tls-private-key-file=/admission.local.config/certificates/tls.key
            - --ca-cert-file=/admission.local.config/certificates/ca.crt
            - --mutate-webhook-config-name={{ .Release.Name }}-mutate-job
            - --validate-webhook-config-name={{ .Release.Name }}-validate-job
            - --alsologtostderr
            - --port=443
            - -v=4
            - 2>&1
          image: {{.Values.basic.admission_image_name}}:{{.Values.basic.image_tag_version}}
          imagePullPolicy: IfNotPresent
          name: admission
          volumeMounts:
            - mountPath: /admission.local.config/certificates
              name: admission-certs
              readOnly: true
      volumes:
        - name: admission-certs
          secret:
            defaultMode: 420
            secretName: {{.Values.basic.admission_secret_name}}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    test: admission
  name: {{ .Release.Name }}-admission-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    admission: "true"
  sessionAffinity: None
