---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: nodeshards.shard.volcano.sh
spec:
  group: shard.volcano.sh
  names:
    kind: NodeShard
    listKind: NodeShardList
    plural: nodeshards
    shortNames:
    - nsh
    singular: nodeshard
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.schedulerName
      name: SCHEDULER
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NodeShard is a collection of nodes dedicated to a specific scheduler
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Specification of the desired behavior of the NodeShard.
            properties:
              nodesDesired:
                description: |-
                  NodesDesired defines the list of nodes desired to be included in this NodeShard.
                  Required.
                items:
                  type: string
                type: array
              schedulerName:
                description: |-
                  SchedulerName indicates which scheduler should handle this NodeShard.
                  Required.
                type: string
            required:
            - nodesDesired
            - schedulerName
            type: object
          status:
            description: |-
              Status represents the current information about a NodeShard.
              This data may not be up to date.
            properties:
              lastUpdateTime:
                description: LastUpdateTime is the last time the status was updated.
                format: date-time
                type: string
              nodesInUse:
                description: NodesInUse is the list of nodes currently in use by the
                  NodeShard.
                items:
                  type: string
                type: array
              nodesToAdd:
                description: NodesToAdd is the list of nodes preparing to be added
                  to the NodeShard.
                items:
                  type: string
                type: array
              nodesToRemove:
                description: NodesToRemove is the list of nodes preparing to be removed
                  from the NodeShard.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
