
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.0
  creationTimestamp: null
  name: jobflows.flow.volcano.sh
spec:
  group: flow.volcano.sh
  names:
    kind: JobFlow
    listKind: JobFlowList
    plural: jobflows
    shortNames:
    - jf
    singular: jobflow
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JobFlow is the Schema for the jobflows API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JobFlowSpec defines the desired state of JobFlow
            properties:
              flows:
                description: Foo is an example field of JobFlow. Edit jobflow_types.go
                  to remove/update
                items:
                  description: Flow defines the dependent of jobs
                  properties:
                    dependsOn:
                      properties:
                        probe:
                          properties:
                            httpGetList:
                              items:
                                properties:
                                  httpHeader:
                                    description: HTTPHeader describes a custom header
                                      to be used in HTTP probes
                                    properties:
                                      name:
                                        description: The header field name. This will
                                          be canonicalized upon output, so case-variant
                                          names will be understood as the same header.
                                        type: string
                                      value:
                                        description: The header field value
                                        type: string
                                    required:
                                    - name
                                    - value
                                    type: object
                                  path:
                                    type: string
                                  port:
                                    type: integer
                                  taskName:
                                    type: string
                                type: object
                              type: array
                            taskStatusList:
                              items:
                                properties:
                                  phase:
                                    type: string
                                  taskName:
                                    type: string
                                type: object
                              type: array
                            tcpSocketList:
                              items:
                                properties:
                                  port:
                                    type: integer
                                  taskName:
                                    type: string
                                required:
                                - port
                                type: object
                              type: array
                          type: object
                        targets:
                          items:
                            type: string
                          type: array
                      type: object
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              jobRetainPolicy:
                type: string
            type: object
          status:
            description: JobFlowStatus defines the observed state of JobFlow
            properties:
              completedJobs:
                items:
                  type: string
                type: array
              conditions:
                additionalProperties:
                  properties:
                    createTime:
                      format: date-time
                      type: string
                    phase:
                      description: JobPhase defines the phase of the job.
                      type: string
                    runningDuration:
                      type: string
                    taskStatusCount:
                      additionalProperties:
                        description: TaskState contains details for the current state
                          of the task.
                        properties:
                          phase:
                            additionalProperties:
                              format: int32
                              type: integer
                            description: The phase of Task.
                            type: object
                        type: object
                      type: object
                  type: object
                type: object
              failedJobs:
                items:
                  type: string
                type: array
              jobStatusList:
                items:
                  properties:
                    endTimestamp:
                      format: date-time
                      type: string
                    name:
                      type: string
                    restartCount:
                      format: int32
                      type: integer
                    runningHistories:
                      items:
                        properties:
                          endTimestamp:
                            format: date-time
                            type: string
                          startTimestamp:
                            format: date-time
                            type: string
                          state:
                            description: JobPhase defines the phase of the job.
                            type: string
                        type: object
                      type: array
                    startTimestamp:
                      format: date-time
                      type: string
                    state:
                      description: JobPhase defines the phase of the job.
                      type: string
                  type: object
                type: array
              pendingJobs:
                items:
                  type: string
                type: array
              runningJobs:
                items:
                  type: string
                type: array
              state:
                properties:
                  phase:
                    type: string
                type: object
              terminatedJobs:
                items:
                  type: string
                type: array
              unKnowJobs:
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
