
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: queues.scheduling.volcano.sh
spec:
  group: scheduling.volcano.sh
  names:
    kind: Queue
    listKind: QueueList
    plural: queues
    shortNames:
    - q
    - queue-v1beta1
    singular: queue
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Queue is a queue of PodGroup.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
          type: object
        spec:
          description: 'Specification of the desired behavior of the queue. More info:
            https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            capability:
              additionalProperties:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              description: ResourceList is a set of (resource name, quantity) pairs.
              type: object
            reclaimable:
              description: Reclaimable indicate whether the queue can be reclaimed
                by other queue
              type: boolean
            weight:
              format: int32
              type: integer
          type: object
        status:
          description: The status of queue.
          properties:
            inqueue:
              description: The number of `Inqueue` PodGroup in this queue.
              format: int32
              type: integer
            pending:
              description: The number of 'Pending' PodGroup in this queue.
              format: int32
              type: integer
            running:
              description: The number of 'Running' PodGroup in this queue.
              format: int32
              type: integer
            state:
              description: State is state of queue
              type: string
            unknown:
              description: The number of 'Unknown' PodGroup in this queue.
              format: int32
              type: integer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
