apiVersion: v1
description: A Helm chart for Volcano
name: volcano
version: 1.5
appVersion: 0.1
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano
maintainers:
  - name: k82cn
    email: klaus1982.cn@gmail.com
  - name: kevin-wangzefeng
    email: kevinwzf0126@gmail.com
