apiVersion: v1
description: A Helm chart for Volcano
name: volcano
version: 1.7.0-beta.0
appVersion: 0.1
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano
maintainers:
  - name: william-wang
    email: wang.platform@gmail.com
  - name: kevin-wangzefeng
    email: kevinwzf0126@gmail.com
