basic:
  image_tag_version: "v1.5.1-spotify.2"
  controller_image_name: "ghcr.io/spotify/volcano/vc-controller-manager"
  scheduler_image_name: "ghcr.io/spotify/volcano/vc-scheduler"
  admission_image_name: "ghcr.io/spotify/volcano/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"

  image_pull_secret: ""
  admission_port: 8443
custom:
  metrics_enable: "false"
