basic:
  image_tag_version: "v1.4.1"
  controller_image_name: "volcanosh/vc-controller-manager"
  scheduler_image_name: "volcanosh/vc-scheduler"
  admission_image_name: "volcanosh/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"

  image_pull_secret: ""
  admission_port: 8443
  crd_version: "v1beta1"
custom:
  metrics_enable: "false"
