basic:
  controller_image_name: "volcanosh/vc-controller-manager"
  scheduler_image_name: "volcanosh/vc-scheduler"
  admission_image_name: "volcanosh/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  admission_config_file: "config/volcano-admission.conf"
  scheduler_config_file: "config/volcano-scheduler.conf"
  image_pull_secret: ""
  image_pull_policy: "Always"
  image_tag_version: "latest"
  admission_port: 8443
custom:
  metrics_enable: false
  admission_enable: true
  admission_replicas: 1
  controller_enable: true
  controller_replicas: 1
  scheduler_enable: true
  scheduler_replicas: 1
  leader_elect_enable: false
  enabled_admissions: "/jobs/mutate,/jobs/validate,/podgroups/mutate,/pods/validate,/pods/mutate,/queues/mutate,/queues/validate"
nodeSelector: {}
affinity: []
tolerations: []
# installCRDs -- If true, CRD resources will be installed as part of the Helm chart. If enabled, when uninstalling CRD resources will be deleted causing all installed custom resources to be DELETED
installCRDs: true
