name: E2E Parallel Jobs

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  e2e_parallel_jobs:
    runs-on: ubuntu-24.04
    name: E2E about Parallel Jobs
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependences
        run: |
          GO111MODULE="on" go install sigs.k8s.io/kind@v0.24.0
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubectl && sudo install kubectl /usr/local/bin/kubectl
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run E2E Tests
        run: |
          make e2e-test-jobp CC=/usr/local/musl/bin/musl-gcc

      - name: export logs for e2e parallel jobs
        if: failure()
        run: |
          export ARTIFACTS_PATH=${{ github.workspace }}/e2e-parallel-jobs-logs
          mkdir -p $ARTIFACTS_PATH
          
          mkdir -p $ARTIFACTS_PATH/integration
          kind export logs --name=integration $ARTIFACTS_PATH/integration

      - name: upload e2e parallel jobs logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: volcano_e2e_parallel_jobs_logs
          path: ${{ github.workspace }}/e2e-parallel-jobs-logs
