name: E2E Sequence Jobs

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  e2e_sequence:
    runs-on: ubuntu-18.04
    name: E2E about Sequence
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependences
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.11.0
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl && sudo install kubectl /usr/local/bin/kubectl
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run E2E Tests
        run: |
          make images CC=/usr/local/musl/bin/musl-gcc
          make e2e-test-jobseq